# Generated by Django 4.2.3 on 2023-07-31 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_subject_file_subject_image_subject_link_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos_uploaded')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='file',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='link',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video',
        ),
        migrations.AddField(
            model_name='subject',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.media'),
        ),
    ]
