# Generated by Django 4.2.3 on 2023-07-31 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_media_remove_subject_file_remove_subject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.media'),
        ),
    ]
