# Generated by Django 4.2.3 on 2023-07-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_media_name_alter_subject_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='studies.subject'),
        ),
    ]
