# Generated by Django 4.2.4 on 2023-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_major_settings_subject_section_subject_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Major',
            new_name='major',
        ),
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
