# Generated by Django 4.2.4 on 2023-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_rename_major_subject_major_alter_subject_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
