# Generated by Django 4.2.4 on 2023-08-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
