# Generated by Django 4.2.4 on 2023-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='image',
            field=models.ImageField(default='../college/static/images/lect.jpg', upload_to=''),
        ),
    ]
