# Generated by Django 4.2.4 on 2023-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_major_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='image',
            field=models.ImageField(default='../media/lect.jpg', upload_to=''),
        ),
    ]
