# Generated by Django 4.2.4 on 2023-08-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_alter_major_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='major',
            name='image',
            field=models.ImageField(blank=True, default='../media/lect.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='media',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='studies.section'),
        ),
    ]
