# Generated by Django 4.2.4 on 2023-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_section_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='settings',
            new_name='setting',
        ),
        migrations.AddField(
            model_name='section',
            name='isPublic',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
