# Generated by Django 4.2.4 on 2023-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_alter_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='canAccess',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
