# Generated by Django 4.2.4 on 2023-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_email_canaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='canAccess',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
